### ISSUE TITLE
Create HomeScreen

### ISSUE THREAD

**Issue by PipocaAgilDevs** [PipocaAgilDevs/cigarro-zero-app#3]

**Comment by PipocaAgilDevs** [comment]
- [x] Create Header Component  #5 
- [ ] Create Navbar Component #6 
- [x] Create Body Component #7
